-- CreateEnum
CREATE TYPE "EmployeeContractType" AS ENUM ('EN_BLANCO', 'MONOTRIBUTO', 'INFORMAL');

-- CreateEnum
CREATE TYPE "EmployeeVariableType" AS ENUM ('NINGUNO', 'MONTO_POR_EVENTO', 'COMISION_PCT');

-- CreateTable
CREATE TABLE "tenant_cost_configs" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "gananciaPct" DECIMAL(5,4) NOT NULL DEFAULT 0.40,
    "roturaPct" DECIMAL(5,4) NOT NULL DEFAULT 0.15,
    "ivaPct" DECIMAL(5,4) NOT NULL DEFAULT 0.21,
    "insumoRenegotiationPct" DECIMAL(5,4) NOT NULL DEFAULT 0.10,
    "advanceDepositCapPct" DECIMAL(5,4) NOT NULL DEFAULT 0.30,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tenant_cost_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "supply_categories" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "supply_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event_supply_lines" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,
    "productName" TEXT NOT NULL,
    "presentation" TEXT,
    "quantity" DECIMAL(10,3) NOT NULL,
    "unitCost" DECIMAL(12,2) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "event_supply_lines_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_cost_categories" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "service_cost_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event_service_costs" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "categoryId" TEXT,
    "employeeId" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "manuallyEdited" BOOLEAN NOT NULL DEFAULT false,
    "amount" DECIMAL(12,2) NOT NULL,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "event_service_costs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "fixed_cost_categories" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "monthlyAmount" DECIMAL(12,2) NOT NULL,
    "guestScaled" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "fixed_cost_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "employees" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "contractType" "EmployeeContractType" NOT NULL,
    "fixedMonthlyAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "variableType" "EmployeeVariableType" NOT NULL DEFAULT 'NINGUNO',
    "variableValue" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "employees_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event_staff_assignments" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "event_staff_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "employee_time_entries" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "hours" DECIMAL(5,2),
    "note" TEXT,
    "eventId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "employee_time_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payroll_entries" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "period" TIMESTAMP(3) NOT NULL,
    "fixedComponent" DECIMAL(12,2) NOT NULL,
    "variableComponent" DECIMAL(12,2) NOT NULL,
    "advancesDeducted" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "note" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payroll_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "employee_commission_advances" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "eventId" TEXT,
    "note" TEXT,
    "reconciledInEntryId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "employee_commission_advances_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "tenant_cost_configs_tenantId_key" ON "tenant_cost_configs"("tenantId");

-- CreateIndex
CREATE INDEX "tenant_cost_configs_tenantId_idx" ON "tenant_cost_configs"("tenantId");

-- CreateIndex
CREATE INDEX "supply_categories_tenantId_idx" ON "supply_categories"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "supply_categories_tenantId_name_key" ON "supply_categories"("tenantId", "name");

-- CreateIndex
CREATE INDEX "event_supply_lines_tenantId_idx" ON "event_supply_lines"("tenantId");

-- CreateIndex
CREATE INDEX "event_supply_lines_tenantId_productName_idx" ON "event_supply_lines"("tenantId", "productName");

-- CreateIndex
CREATE INDEX "service_cost_categories_tenantId_idx" ON "service_cost_categories"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "service_cost_categories_tenantId_name_key" ON "service_cost_categories"("tenantId", "name");

-- CreateIndex
CREATE INDEX "event_service_costs_tenantId_idx" ON "event_service_costs"("tenantId");

-- CreateIndex
CREATE INDEX "fixed_cost_categories_tenantId_idx" ON "fixed_cost_categories"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "fixed_cost_categories_tenantId_name_key" ON "fixed_cost_categories"("tenantId", "name");

-- CreateIndex
CREATE INDEX "employees_tenantId_idx" ON "employees"("tenantId");

-- CreateIndex
CREATE INDEX "event_staff_assignments_tenantId_idx" ON "event_staff_assignments"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "event_staff_assignments_eventId_employeeId_key" ON "event_staff_assignments"("eventId", "employeeId");

-- CreateIndex
CREATE INDEX "employee_time_entries_tenantId_idx" ON "employee_time_entries"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "employee_time_entries_employeeId_date_key" ON "employee_time_entries"("employeeId", "date");

-- CreateIndex
CREATE INDEX "payroll_entries_tenantId_idx" ON "payroll_entries"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "payroll_entries_employeeId_period_key" ON "payroll_entries"("employeeId", "period");

-- CreateIndex
CREATE INDEX "employee_commission_advances_tenantId_idx" ON "employee_commission_advances"("tenantId");

-- AddForeignKey
ALTER TABLE "event_supply_lines" ADD CONSTRAINT "event_supply_lines_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_supply_lines" ADD CONSTRAINT "event_supply_lines_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "supply_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_service_costs" ADD CONSTRAINT "event_service_costs_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_service_costs" ADD CONSTRAINT "event_service_costs_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "service_cost_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_service_costs" ADD CONSTRAINT "event_service_costs_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_staff_assignments" ADD CONSTRAINT "event_staff_assignments_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event_staff_assignments" ADD CONSTRAINT "event_staff_assignments_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employee_time_entries" ADD CONSTRAINT "employee_time_entries_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employee_time_entries" ADD CONSTRAINT "employee_time_entries_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payroll_entries" ADD CONSTRAINT "payroll_entries_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employee_commission_advances" ADD CONSTRAINT "employee_commission_advances_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employee_commission_advances" ADD CONSTRAINT "employee_commission_advances_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employee_commission_advances" ADD CONSTRAINT "employee_commission_advances_reconciledInEntryId_fkey" FOREIGN KEY ("reconciledInEntryId") REFERENCES "payroll_entries"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- Row-Level Security — regla obligatoria de CLAUDE.md: RLS + GRANT en la
-- misma migración que crea la tabla, nunca después.
-- ============================================================================

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'tenant_cost_configs', 'supply_categories', 'event_supply_lines',
    'service_cost_categories', 'event_service_costs', 'fixed_cost_categories',
    'employees', 'event_staff_assignments', 'employee_time_entries',
    'payroll_entries', 'employee_commission_advances'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING ("tenantId" = current_setting(''app.tenant_id'', true)) WITH CHECK ("tenantId" = current_setting(''app.tenant_id'', true))',
      t
    );
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO app_user', t);
  END LOOP;
END
$$;
