// Schemas y tipos del módulo de costeo (Plan Pro) — ver CLAUDE.md "Fase 2 —
// costeo y personal" para el detalle de las decisiones de negocio. Mismo
// criterio que admin.ts: input = Zod, respuestas = interfaces planas.

import { z } from 'zod';
import { SupplyUnitSchema } from './enums';
import { optionalText } from './zodHelpers';

export const TenantCostConfigInputSchema = z.object({
  gananciaPct: z.coerce.number().min(0).max(5),
  roturaPct: z.coerce.number().min(0).max(5),
  ivaPct: z.coerce.number().min(0).max(5),
  insumoRenegotiationPct: z.coerce.number().min(0).max(5),
  advanceDepositCapPct: z.coerce.number().min(0).max(1),
});
export type TenantCostConfigInput = z.infer<typeof TenantCostConfigInputSchema>;

export const SupplyCategoryInputSchema = z.object({
  name: z.string().trim().min(1, 'Ingresá un nombre').max(120),
  sortOrder: z.coerce.number().int().min(0).max(9999).default(0),
});
export type SupplyCategoryInput = z.infer<typeof SupplyCategoryInputSchema>;

export const ServiceCostCategoryInputSchema = z.object({
  name: z.string().trim().min(1, 'Ingresá un nombre').max(120),
});
export type ServiceCostCategoryInput = z.infer<typeof ServiceCostCategoryInputSchema>;

export const FixedCostCategoryInputSchema = z.object({
  name: z.string().trim().min(1, 'Ingresá un nombre').max(120),
  monthlyAmount: z.coerce.number().min(0).max(1_000_000_000),
  guestScaled: z.coerce.boolean().default(false),
});
export type FixedCostCategoryInput = z.infer<typeof FixedCostCategoryInputSchema>;

export const EventSupplyLineInputSchema = z.object({
  categoryId: z.string().trim().min(1, 'Elegí un rubro'),
  productName: z.string().trim().min(1, 'Ingresá el producto').max(160),
  quantity: z.coerce.number().positive().max(1_000_000),
  unit: SupplyUnitSchema,
  unitCost: z.coerce.number().min(0).max(1_000_000_000),
});
export type EventSupplyLineInput = z.infer<typeof EventSupplyLineInputSchema>;

export const EventServiceCostInputSchema = z.object({
  categoryId: optionalText(z.string().trim().min(1)),
  employeeId: optionalText(z.string().trim().min(1)),
  amount: z.coerce.number().min(0).max(1_000_000_000),
  note: optionalText(z.string().trim().max(200)),
});
export type EventServiceCostInput = z.infer<typeof EventServiceCostInputSchema>;

export interface TenantCostConfigSummary {
  gananciaPct: number;
  roturaPct: number;
  ivaPct: number;
  insumoRenegotiationPct: number;
  advanceDepositCapPct: number;
}

export interface SupplyCategorySummary {
  id: string;
  name: string;
  sortOrder: number;
}

export interface ServiceCostCategorySummary {
  id: string;
  name: string;
}

export interface FixedCostCategorySummary {
  id: string;
  name: string;
  monthlyAmount: number;
  guestScaled: boolean;
}

export interface EventSupplyLineSummary {
  id: string;
  categoryId: string;
  categoryName: string;
  productName: string;
  quantity: number;
  unit: 'KG' | 'LITROS' | 'UNIDAD';
  unitCost: number;
  lineCost: number;
  /** true si unitCost supera insumoRenegotiationPct vs. la última carga del
   *  mismo producto en el tenant — solo informativo, nunca bloquea nada. */
  renegotiationWarning: boolean;
}

export interface EventServiceCostSummary {
  id: string;
  categoryId: string | null;
  categoryName: string | null;
  employeeId: string | null;
  employeeName: string | null;
  autoGenerated: boolean;
  amount: number;
  note: string | null;
}

/** Cálculo completo de costeo de un evento — ver la fórmula documentada en
 *  CLAUDE.md "Fase 2 — costeo y personal". */
export interface EventCostingSummary {
  guestCount: number;
  eventsInMonth: number;
  supplyLines: EventSupplyLineSummary[];
  serviceCosts: EventServiceCostSummary[];
  fixedCostBreakdown: { categoryName: string; proratedAmount: number }[];
  totalSupplyCost: number;
  totalServiceCost: number;
  totalFixedCostProrated: number;
  costoNeto: number;
  costoPor100Invitados: number;
  costoTarjeta: number;
}
